/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StructsFileUpload } from './structsFileUpload';
import { StructsReplyButton } from './structsReplyButton';


export interface StructsButtonMessageWithMediaPayload { 
    buttons?: Array<StructsReplyButton>;
    footer_text?: string;
    media_data?: StructsFileUpload;
    text?: string;
    to?: string;
}

