/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileUpload { 
    direct_path: string;
    file_enc_sha256: Array<number>;
    file_length: number;
    file_sha256: Array<number>;
    media_key: Array<number>;
    mime_type: string;
    url: string;
}

