/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LocationMessagePayloadLocation } from './locationMessagePayloadLocation';


export interface LocationMessagePayload { 
    location: LocationMessagePayloadLocation;
    to: string;
    url?: string;
}

