/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TemplateButton } from './templateButton';


export interface TemplateButtonPayload { 
    buttons: Array<TemplateButton>;
    content_text?: string;
    footer?: string;
    header?: string;
    to: string;
}

